# Generated by Django 3.0 on 2019-12-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_okr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
